
site_name: zeeSQL
repo_url: https://github.com/RedBeardLab/zeeSQL-doc
google_analytics:
  - UA-116709819-1
  - auto

pages:
  -
    Overview: README.md
  -
    Tutorials:
      - 'Tutorial': tutorial.md
  -
    References: references.md
        #  -
        #    Pro: pro.md
        #  -
        #    Motivations: motivations.md
  -
    Pricing: pricing.md
        #    Blog:
        #      - 'Release 0.9.0': 'blog/release_0.9.0.md'
        #      - 'Release 0.8.0': 'blog/release_0.8.0.md'
        #      - 'Release 0.7.0': 'blog/release_0.7.0.md'
        #      - 'Release 0.6.0': 'blog/release_0.6.0.md'
        #      - 'Release 0.5.0': 'blog/release_0.5.0.md'
        #      - 'Analytics': 'blog/analytics.md'
        #      - 'JSON on Redis using RediSQL, SQL steroids for Redis': 'blog/JaaS.md'
        #      - 'Double performances of RediSQL going zero copy': 'blog/performances.md'
        #      - 'Using RediSQL with Python': 'blog/python/using-redisql-with-python.md'
        #      - 'Using RediSQL with Go(lang)': 'blog/golang/using-redisql-with-golang.md'
        #      - 'Using RediSQL with Node.js': 'blog/node/using-redisql-with-node.md'
        #  -
        #    FAQs: faqs.md
